# CS3DM - Lab 3

## Objectives
To explore Pandas and the _Series_, _DataFrame_ and _Index_ objects, and to gain some familiarity with the use of Pandas for exploratory analysis.

## Suggested Reading
Jake VandePlas, *Python Data Science Handbook*, Chapter 3: <https://jakevdp.github.io/PythonDataScienceHandbook/>\

## Acknowledgments
Some of the examples in this unit are taken from: [Python Crash Course - A Hands-on, Project-based, introduction to programming](https://nostarch.com/pythoncrashcourse2e)

## Instructions
This is a follow-on tutorial. There are a few _**TO DO**_ blocks, but most of this tutorial is for you to follow through. Please take your time at each block to understand what is being done, and feel free to tinker, explore and modify any block to check your understanding (if you break anything you can always ctrl-Z, or in the worst case download the original Notebook again).
*****

# Pandas data structures

## What is Pandas
Pandas is a package built on top of NumPy, which provides an efficient implementation of a data frame (or, as it is called in Pandas, a `DataFrame`). Pandas' DataFrames are multidimensional arrays with attached row and column labels, can contain heterogeneous data types and missing data. Pandas implements a number of powerful data operations for transforming and merging data and, besides `DataFrame`, it also provides two other useful data objects: `Series` and `Index`.

## `Series` objects
A Pandas `Series` is a one-dimensional array of indexed data. It can be easily created from a list or array.

In [2]:
import numpy as np
import pandas as pd
mydata = pd.Series([.0, .5, 1.])
print(mydata)

0    0.0
1    0.5
2    1.0
dtype: float64

Notice that the `Series` explicitly stores data as `<index-value>` pairs. Indices can be used later to access the values.

Values in a Series object can be accessed the intuitive way:

In [3]:
print(mydata.values)
print(mydata.index)
mydata[0]

[0.  0.5 1. ]
RangeIndex(start=0, stop=3, step=1)

np.float64(0.0)

The essential difference between a `Series` and a NumPy 1D array is the index: 
  - The NumPy Array has an (implicitly defined) integer index used to access the values
  - The Pandas Series has an (explicitly defined) index associated with the values.

This gives `Series` objects additional capabilities, e.g., generalising the index to any type (useful if we want to index by label). It is also possible to see `Series` as a specialised Python dictionary: a dictionary maps arbitrary keys to a set of arbitrary values, and a `Series` maps typed keys to a set of typed values. 

The _typing_ of the keys and values is important: the type information of `Series` makes it much more efficient than Python dictionaries for certain operations.

In [4]:
mydata = pd.Series(data = [0.25, 0.5, 0.75], index=['1Q', '2Q', '3Q']) # build series with nominal indices

print(mydata['2Q']) # index by label
print("-----")

user_dict = {'login': 'fcampelo', 'first': 'felipe', 'last': 'campelo'} # build a dictionary
user_series = pd.Series(user_dict)# convert it to a Pandas series
print(user_dict)
print("-----")
print(user_series)

0.5
-----
{'login': 'fcampelo', 'first': 'felipe', 'last': 'campelo'}
-----
login    fcampelo
first      felipe
last      campelo
dtype: object

In [5]:
user_series['first':] # Unlike a dictionary, you can do slicing on `Series`

first     felipe
last     campelo
dtype: object

## `DataFrame` objects

Another fundamental structure in Pandas is the `DataFrame`, which is possibly one of the most usefult for data science. Like the `Series` objects, the `DataFrame` can also be seen as generalised 2D NumPy array or, alternatively, as a specialised Python dictionary. 

A `DataFrame` can be seen as an analog of a 2D NumPy array, with flexible row indices and column names. It may be useful to think of a DataFrame as a sequence of Series objects that share the same index - i.e., that are, in a sense, aligned.

In [6]:
area = pd.Series({'CA': 423967, 'TX': 695662, 'NY': 141297})
population = pd.Series({'CA': 38332521, 'TX': 26448193, 'NY': 19651127})

mydata = pd.DataFrame({'population': population, 'area': area})
mydata

    population    area
CA    38332521  423967
TX    26448193  695662
NY    19651127  141297

Like `Series`, the `DataFrame` has an `index` attribute that gives access to the row (observation) labels. Additionally, it also has a `columns` attribute, which holds the column (variable) labels. This is why it can be seen as a generalised 2D NumPy array, where both rows and columns have a (generalised) index for accessing the data.

In [7]:
print(mydata.index)
print(mydata.columns)

Index(['CA', 'TX', 'NY'], dtype='object')
Index(['population', 'area'], dtype='object')

In [8]:
# We can also build a `DataFrame` from a dictionary (or a list of dictionaries, a dictionary of `Series`, a 2D NumPy array, etc.)
data = {'name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 
        'age': [42, 52, 36, 24, 73], 
        'preTestScore': [4, 24, 31, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70]}
df = pd.DataFrame(data)
df

    name  age  preTestScore  postTestScore
0  Jason   42             4             25
1  Molly   52            24             94
2   Tina   36            31             57
3   Jake   24             2             62
4    Amy   73             3             70

## `Index` objects
The third type of Pandas object is the `Index`. Both `Series` and `DataFrame` objects contain an explicit index that lets you reference and modify data. This `Index` object can be thought of either as an immutable array or as an ordered (multi-)set, which results in some interesting operations that can be performed on these objects.

In [9]:
ind = pd.Index([1, 1, 2, 3, 5, 8, 13]) # Build `Index` object
print(ind)

# We can use standard Python indexing notation to retrieve values or slices:
print(ind[3])
print(ind[1::2])

Index([1, 1, 2, 3, 5, 8, 13], dtype='int64')
3
Index([1, 3, 8], dtype='int64')

Index objects have many of the attributes familiar from NumPy arrays. One important difference between Index objects and NumPy arrays is that indices are **immutable**, which means that they cannot be modified as an array would. As we're going to see later, Pandas objects are designed to facilitate operations such as joins across datasets, and as such unions, intersections, differences, and other combinations of datasets can be computed relatively easily.

In [10]:
ind2 = pd.Index(np.arange(0,7))

print(ind.intersection(ind2)) # intersection
print("-----")
print(ind.union(ind2)) # union

Index([1, 2, 3, 5], dtype='int64')
-----
Index([0, 1, 1, 2, 3, 4, 5, 6, 8, 13], dtype='int64')

## Indexing in `Series`
The slicing and indexing conventions in `Series` can be a source of confusion. For example, if the `Series` has an explicit integer index, an indexing operation such as `data[1]` will use the explicit indices, while a slicing operation like `data[1:3]` will use the implicit, Python-style index:

In [11]:
mydata = pd.Series(data = ['a', 'b', 'c', 'd'], index=[3, 2, 1, 0])

print(mydata[0])   # explicit index when indexing
print("-----")
print(mydata[0:2]) # implicit index when slicing

d
-----
3    a
2    b
dtype: object

Because of this potential confusion, Pandas provides some special indexer attributes that explicitly expose certain indexing schemes. These are not functional methods, but attributes that expose a particular slicing interface to the data in the Series. 

The `loc` attribute allows indexing and slicing that **always** reference the explicit index:

In [12]:
print(mydata.loc[0])
print("-----")
print(mydata.loc[0:2])    # This won't work well
print("-----")
print(mydata.loc[0:2:-1]) # But this will

d
-----
Series([], dtype: object)
-----
0    d
1    c
2    b
dtype: object

Similarly, The `iloc` attribute allows indexing and slicing that **always** reference the implicit, Python-style index:

In [13]:
print(mydata.iloc[0])
print("-----")
print(mydata.iloc[0:2])

a
-----
3    a
2    b
dtype: object

## Data Selection in `DataFrames`
Recall that a `DataFrame` acts in many ways like a 2D array, and in other ways like a dictionary of `Series` structures sharing a common index.

In [14]:
# Rebuild the US States population data frame:
area = pd.Series({'CA': 423967, 'TX': 695662, 'NY': 141297})
population = pd.Series({'CA': 38332521, 'TX': 26448193, 'NY': 19651127})
mydata = pd.DataFrame({'population': population, 'area': area})

# The individual `Series` that make up the columns of the `DataFrame` can be accessed using:
print(mydata['population'])
print("-----")
print(mydata.population)    # equivalent(-ish; see below)

# Create a new attribute in the dataframe:
mydata['density'] = mydata['population'] / mydata['area']
print("-----")
print(mydata)

CA    38332521
TX    26448193
NY    19651127
Name: population, dtype: int64
-----
CA    38332521
TX    26448193
NY    19651127
Name: population, dtype: int64
-----
    population    area     density
CA    38332521  423967   90.413926
TX    26448193  695662   38.018740
NY    19651127  141297  139.076746

**Note**: although the ".column" notation is useful, it does not always work! If the column names are not strings, or if they conflict with methods of the `DataFrame`, this attribute-style access is not possible.

The raw underlying data array in a `DataFrame` can be examined using the `.values` attribute. This 2D array aspect of the `DataFrame` makes many familiar array-like operations possible on the `DataFrame` itself.

In [23]:
print(mydata.values)
print("-----")
print(mydata.T) # transpose, like a matrix

[[3.83325210e+07 4.23967000e+05 9.04139261e+01]
 [2.64481930e+07 6.95662000e+05 3.80187404e+01]
 [1.96511270e+07 1.41297000e+05 1.39076746e+02]]
-----
                      CA            TX            NY
population  3.833252e+07  2.644819e+07  1.965113e+07
area        4.239670e+05  6.956620e+05  1.412970e+05
density     9.041393e+01  3.801874e+01  1.390767e+02

## Indexing in `DataFrames`

When it comes to indexing of DataFrame objects, the dictionary-style indexing of columns precludes our ability to simply treat it as a NumPy array. In particular, passing a single index to an array accesses a row, but for a DataFrame we get a column instead.

For array-style indexing of `DataFrame`s we can use the `loc` and `iloc` indexers.
- Using `iloc` we index the underlying array as a simple NumPy array, but the DataFrame index and column labels are maintained.
- Using `loc` we index the underlying data in an array-like style, but using the explicit index and column names instead.

In [20]:
print(mydata.iloc[:2, 1]) # by numerical indices
print("-----")
print(mydata.loc['TX':'NY', :'population']) # by row/column labels

CA    423967
TX    695662
Name: area, dtype: int64
-----
    population
TX    26448193
NY    19651127

Any of the NumPy-style data access patterns can be used within these indexers. For example, in the `loc` indexer we can combine masking and fancy indexing:

In [ ]:
mydata.loc[mydata.density > 100,      # Get places with density above 100
           ['population', 'density']] # Select only these two columns

***
### **TO DO**
(5 minutes)
- Create a simple Pandas Series from a list containing your 4 favourite university modules until now. Make sure you know how to access its elements by either position or index.
- Create a second Pandas Series containing the names of the module leaders for the modules in your first list.
- Build a Pandas DataFrame from the two Series above
- Add a new variable to your DataFrame, with your final results in those modules ('pass', 'merit', 'distinction')
- Extract and print the full second row of your DataFrame
- Extract and print the variable containing your final results.

In [25]:
# Write your solution here
module_series = pd.Series(data = ['DC3IPR','DC3DMN', 'DC3ISC', 'DC3IDG'], index = [1,2,3,4])
leader_series = pd.Series(data = ['Tutor A', 'Tutor B', 'Tutor C', 'Tutor B'], index = [1,2,3,4])
print(module_series)
print(leader_series)
df_module_information = pd.DataFrame({'Module' : module_series, 'Leader' : leader_series})
print(df_module_information)
df_module_information['Results'] = ['Distinction', 'Pass', 'Merit', 'Distinction']
print(df_module_information)
print(df_module_information.loc['1': '4','Results'])
print(df_module_information.iloc[2: 3])

1    DC3IPR
2    DC3DMN
3    DC3ISC
4    DC3IDG
dtype: object
1    Tutor A
2    Tutor B
3    Tutor C
4    Tutor B
dtype: object
   Module   Leader
1  DC3IPR  Tutor A
2  DC3DMN  Tutor B
3  DC3ISC  Tutor C
4  DC3IDG  Tutor B
   Module   Leader      Results
1  DC3IPR  Tutor A  Distinction
2  DC3DMN  Tutor B         Pass
3  DC3ISC  Tutor C        Merit
4  DC3IDG  Tutor B  Distinction
1    Distinction
2           Pass
3          Merit
4    Distinction
Name: Results, dtype: object
   Module   Leader Results
3  DC3ISC  Tutor C   Merit

*****
# Working with DataFrames

`DataFrame` objects come equipped with a wealth of mathematican and statistical summary functions and methods, as well as other data manipulation tools that can make life easier when doing data mining. We'll use a simple example data set to explore some of these:

In [31]:
import numpy as np
import pandas as pd
data = {'name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'], 
        'age': [42, 52, 36, 24, 73], 
        'preTestScore': [4, 24, 31, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70]}
        
df = pd.DataFrame(data) # A common convention - "df" stands for "DataFrame"
print(df)

    name  age  preTestScore  postTestScore
0  Jason   42             4             25
1  Molly   52            24             94
2   Tina   36            31             57
3   Jake   24             2             62
4    Amy   73             3             70

We can use the `DataFrame` methods to calculate simple summaries and operations on the data. Note that in the block below we are pointing to one column and then applying a function to that column. Other available methods include `.sum()`, `.cumsum()`, `.prod()`, etc. (if it looks like NumPy, then congratulations - you've been paying attention!)

In [32]:
print([df['age'].min(), df['age'].max()]) # array containing the range of ages
print("-----")

print(df['preTestScore'].mean()) # Average PreTest score

print("-----")
# Summary statistics for a particular column. These can also be obtained isolately using 
# methods`.count()`, `.min()`, `.max()`, `.median()`, `.mean()`, `quantile()`, etc. 
# Other summary statistics, such as `.skew()` and `.kurt()` are also available.
print(df['preTestScore'].describe())

[np.int64(24), np.int64(73)]
-----
12.8
-----
count     5.000000
mean     12.800000
std      13.663821
min       2.000000
25%       3.000000
50%       4.000000
75%      24.000000
max      31.000000
Name: preTestScore, dtype: float64

For a purely numerical `DataFrame` we can treat it as a matrix and calculate, e.g., correlation and covariance matrices for the variables:

In [34]:
print(df.corr())
print("-----")
print(df.cov())

ValueError: could not convert string to float: 'Jason'

We can now start moving to a larger dataset. We'll use the `NYC flights` dataset, which contains data for all flights that departed from NYC airports (JFK, LGA or EWR) in 2013 (CSV file available for download from our Blackboard page). Since it is a pretty large dataset, we'll load it from file rather than typing it by hand:

In [36]:
flights = pd.read_csv("flights.csv")

flights.shape # dimensions of this dataframe (rows and columns).

(336776, 20)

In [37]:
# Check first rows of the dataset
flights.head()

,Unnamed: 0,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,1,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00
1,2,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00
2,3,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00
3,4,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00
4,5,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00

Note that we have a spurious column at the beginning, which we can easily remove:

In [38]:
print(flights.columns)

Index(['Unnamed: 0', 'year', 'month', 'day', 'dep_time', 'sched_dep_time',
       'dep_delay', 'arr_time', 'sched_arr_time', 'arr_delay', 'carrier',
       'flight', 'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour',
       'minute', 'time_hour'],
      dtype='object')

In [39]:
del flights['Unnamed: 0']
print(flights.columns)

Index(['year', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay',
       'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight',
       'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour', 'minute',
       'time_hour'],
      dtype='object')

We can easily extract rows by querying the dataset, using logical operators for more precise queries:

In [ ]:
# All flights departing from EWR on 1 January between 11:00 and 11:59
flights.query("month == 1 & day == 1 & hour == 11 & origin == 'EWR'")

In [ ]:
# Another way to select rows is by indexing or slicing
flights.iloc[1009:1013] # rows 1009 to 1012

To select columns we can use their names. **Notice the use of double brackets**:

In [ ]:
flights[['origin', 'dest', 'month', 'day']].head()

In [ ]:
# Sorts the dataset in ascending order by the first variable. (Additional columns can be used to break ties)
flights.sort_values(by=['distance', 'dest']).head()

# Note: To sort in descending order, just set argument `ascending = False` after the `by` list is finished.

The `.rename` method is used to rename variables using a dictionary.

In [ ]:
flights.rename(columns={'tailnum': 'tail_num'})

It is relatively simple to investigate unique values with `unique()` and remove duplicates using `drop_duplicates()`:

In [ ]:
print(flights.origin.unique())
print("-----")

flights[['origin', 'dest']].drop_duplicates().shape
# This massive dataset contains information from 224 origin-destination routes.

In [ ]:
# Adding new columns calculated from the existing ones is quite straightforward:

flights['gain'] = flights.arr_delay - flights.dep_delay
flights['gain_per_hour'] = flights.gain / (flights.air_time / 60)
flights['speed'] = flights.distance / flights.air_time * 60
flights.columns

Pandas also provides the ability to calculate group summaries:

In [ ]:
# group the observations by the values of variable 'tailnum'
planes_df = flights.groupby('tailnum')     

# Calculate grouped summaries:
delay = planes_df.agg({"origin": "count",     # count of observations in each group. Any variable could have been used for this, we used 'origin'.
                       "distance": "mean",    # mean distance 
                       "arr_delay": "mean"})  # mean delay on arrival

# query resulting dataframe
delay.query("origin > 365 & distance > 2000")

Python's _lambda functions_ are temporary, anonymous functions that can be used once and then discarded. This is useful e.g., when we need a specific summary combining other operations:

In [ ]:
# group by origin airport
destinations = flights.groupby("origin")

X = destinations.agg({
    'tailnum': lambda x: len(x.unique()), # how many distinct planes?
    'origin': 'count'
})

X.rename(columns={'tailnum': 'planes', 'origin': 'flights'})

## Handling missing data
The way in which Pandas handles missing values is constrained by its reliance on the NumPy package, which does not have a built-in notion of NA values for non-floating point data types. Without going into the technical discussions, Pandas essentially employs two already-existing Python null values for representing missing data: the special floating-point `NaN` value, and the Python `None` object. This has some side effects, but in practice it is generally a good way to represent missing data in most cases of interest.

The first `NA` value used by Pandas is `None`, a Python singleton object that is often used for missing data in general Python code. Because it is a Python object, `None` cannot be used in any arbitrary NumPy/Pandas array, but only in arrays with `dtype=object` (i.e., arrays of Python objects). This essentially means that operations on the data will be done at the Python level (instead of the optimised NumPy C code), which generally means (much) slower.

The use of Python objects in an array also means that if you perform aggregations like `sum()` or `min()` across an array with a `None` value, you will generally get an error.

In [ ]:
vals1 = np.array([1, None, 3, 4])
print(vals1)

# vals1.sum() # <---- this would generate an error - try uncommenting it!

The other missing data representation, `NaN`, is a special floating-point value recognized by all systems that use the standard IEEE floating-point representation. NumPy detects `NaN` as a native floating-point type in the array: this array therefore supports the fast NumPy operations executed in compiled code. Pandas is built to handle `NaN` and `None` almost interchangeably, converting between them where appropriate.

NumPy's `NaN` is like covid: highly contageous, and with the potential of being quite annoying in data analysis.

In [ ]:
vals2 = np.array([1, np.nan, 3, 4]) 


print(vals2.mean()) # the presence of a missing value makes the results of mathematical operations also a missing value.

In [ ]:
1 + 2 + np.nan

In [ ]:
# But there are NaN-resistent methods :)
print(np.nanmin(vals2))
print(np.nanmean(vals2))

There are several useful methods for detecting, removing, and replacing missing values (`None` or `NaN`) in Pandas data structures. These are:
  - `isnull()`, generates a boolean mask indicating missing values
  - `notnull()`, generates a boolean mask indicating **non-**missing values
  - `dropna()`, returns a filtered version of the data
  - `fillna()`, returns a copy of the data with missing values filled or imputed

In [ ]:
tmp1 = flights.arr_delay.tail(10) # 10 last values of arr_delay
tmp2 = flights.dep_time.tail(10).isnull()
tmp3 = flights.dep_time.tail(10).notnull()
pd.DataFrame({'Vals' : tmp1, 'Mask' : tmp2, 'NotMask' : tmp3})

In [ ]:
print(flights.arr_delay.tail(15)[7:11])

In [ ]:
print(flights.arr_delay.tail(15)[7:11].dropna())

# Note: Alternatively, you can drop null values along a different axis (e.g., use `axis=1` to drop columns containing a null), 
# drop only rows/columns with all values missing (using option `how='all'`) or only those with more than a given number of nulls 
# (using option `thres`, e.g., `thres=5`).

Using basic imputation routines:

In [ ]:
tmp1 = pd.Series([-1, np.nan, None, 2])
print(tmp1.fillna(0)) # fill with fixed value
print("-----")
print(tmp1.fillna(method = 'ffill')) # forward-fill (uses last non-missing value)
print("-----")
print(tmp1.fillna(method = 'bfill')) # back-fill (uses next non-missing value)

***
### **TO DO**
(15 minutes)
- Reload the flights data set from file 
- Remove column 'Unnamed: 0'.
- Select only observations departing from airport 'JFK'.
- Sort these observations by variables 'carrier', 'day' and 'hour'.
- Calculate the mean delay on departure (variable 'dep_delay') and mean delay on arrival ('arr_delay') for each month. Make sure to write code that ignores missing data when performing these calculations. Print your results to screen.
- Recalculate the mean delay on departure and mean delay on arrival, but this time grouped both by month and by 'carrier'. Print your results to screen.